### ISSUE TITLE
Dead Link in the README.md

### ISSUE THREAD

**Issue by ellerbrock** [GoogleCloudPlatform/k8s-stackdriver#103]
Hi Googlers,

thanks for your great work and contribution to the open source community!
I just wanted to let you know that you have a 404 in the Readme: [stackdriverSite](https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/stackdriverSite).

![404](https://media.giphy.com/media/GGP4dpOtItmuI/giphy.gif)
Thats all :)

Cheers Maiky

**Comment by x13n** [comment]
Thanks for pointing that out!
@crassirostris you authored the readme file, where was it supposed to point to? https://cloud.google.com/stackdriver/?

**Comment by crassirostris** [comment]
Thanks!
