### ISSUE TITLE
non standard url for prom metrics

### ISSUE THREAD

**Issue by sekhrivijay** [GoogleCloudPlatform/k8s-stackdriver#108]
Is there a way to pull prom metrics from http://localhost/xyx instead of always defaulting to  http://localhost/metrics ?

When I specify 
```
 command:
        - /monitor
        - --source=:http://localhost:80/promMetrics
        - --stackdriver-prefix=custom.googleapis.com
        - --pod-id=$(POD_ID)
        - --namespace-id=$(POD_NAMESPACE)


```
It still defaults to /metrics

**Comment by deejay1** [comment]
@sekhrivijay Ok, I tried to do a patch for that and hope I did it properly and the PR will get merged...
