### ISSUE TITLE
Can't access default stackdriver metrics

### ISSUE THREAD

**Issue by sterchelen** [GoogleCloudPlatform/k8s-stackdriver#146]
Hi,

I can not access stackdriver metrics through http://localhost:8080/apis/external.metrics.k8s.io/v1beta1
- Stackdriver in basic mode.
- 1.9.2-gke.1 version
- Instructions executed.

Any ideas ?

Thank you.

**Comment by kawych** [comment]
Thanks for filing this issue. Can you provide more details? At which point did you get unexpected result?

The endpoint you included is not implemented, the reason being, it would have to include every single metric from Stackdriver. See: https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/custom-metrics-stackdriver-adapter/pkg/adapter/provider/provider.go#L246 It needs some investigation whether it can be safely implemented and for which cases. Have you tried to call http://localhost:8080/apis/external.metrics.k8s.io/v1beta1/namespaces/your-namespace/your-metric-name instead?

Also, can you elaborate on what's your use case for external metrics? I you want to use it for pod autoscaling, please keep in mind that it is not implemented in HPA with 1.9 version.

**Comment by sterchelen** [comment]
Thank for your prompt reply !

I want to use the request count of a load balancer (L7) to autoscale.

http://localhost:8080/apis/external.metrics.k8s.io/v1beta1/namespaces/??/loadbalancing.googleapis.com/https/backend_latencies ?

In 1.10 is it implemented ?

**Comment by kawych** [comment]
Yes, it should work with 1.10 according to my knowledge.

Actually "/" character is not allowed in a metric name included in a path (there are some security reasons for this, generally this rule holds across kubernetes APIs). In Custom Metrics - Stackdriver Adapter "|" character is used instead, so your url would be http://localhost:8080/apis/external.metrics.k8s.io/v1beta1/namespaces/??/loadbalancing.googleapis.com|https|backend_latencies. Looks like it's missing in the documentation, I'll add it to avoid further confusion.

**Comment by sterchelen** [comment]
Great !
I can get metrics :) ! But can I filter on a label ?

**Comment by kawych** [comment]
Yes, you can filter on labels using labelSelector (similarily to custom metrics api). The label names that can be used are specific to Stackdriver (e.g. resource.labels.resoponse_code). This will be covered in documentation for HPA, which is not published yet.

**Comment by sterchelen** [comment]
Thanks a lot !

**Comment by mholleville** [comment]
Hello ! When i'm trying to fetch `backend_latencies` I have this following error . Can you help me ?

```oogleapi: Error 400: Field aggregation.perSeriesAligner had an invalid value of \"ALIGN_RATE\": The aligner cannot be applied to metrics with kind DELTA and value type DISTRIBUTION., badRequest```
