### ISSUE TITLE
[prometheus-to-sd] Support custom paths

### ISSUE THREAD

**Issue by va1en0k** [GoogleCloudPlatform/k8s-stackdriver#159]
Right now the path to `/metrics` is hardcoded in the prometheus-to-sd's source (and it doesn't even seem documented...). Had to do some code-digging to find where I should serve my metrics.

However, I think there should be ways to configure this path. My use-case is that I want to expose two endpoints with different paths: one for pod-level metrics, another one for service-level metrics (the latter are harder to calculate and I want to do it only once per service per interval, not once per pod per interval).

**Comment by x13n** [comment]
We'd like to make prom-to-sd runnable as a DaemonSet, which means it would have to be more configurable than it is today. Your request appears to be a part of that configuration.
cc @loburm @cezarygerard

**Comment by loburm** [comment]
#124 fixes this issue. But we haven't released a new version of prometheus-to-sd that supports it, I'll try to do it next week.

**Comment by va1en0k** [comment]
@x13n that sounds very useful - is there any estimate of the work still needed to make it work as a DaemonSet?

**Comment by x13n** [comment]
Nope, I don't think so. Shouldn't be too hard though.
