### ISSUE TITLE
Empty Stackdriver Traces

### ISSUE THREAD

**Issue by whatupdave** [GoogleCloudPlatform/k8s-stackdriver#16]
I'm on google cloud and some of these tools are running automatically. I've been trying to track down empty traces in Stackdriver Trace and I suspect they're coming from this pod. There's a whole bunch that look like this:

<img width="581" alt="screen shot 2017-07-23 at 3 27 24 pm" src="https://user-images.githubusercontent.com/7064/28503444-b1782f9c-6fbb-11e7-99e5-c2181f2aa9f0.png">

If they're coming from here is it possible to turn them off?

**Comment by crassirostris** [comment]
@whatupdave Interesting, could you please add what's in the report (removed all sensitive information ofc)? What pod exactly is it coming from?

/cc @igorpeshansky

**Comment by whatupdave** [comment]
<img width="1002" alt="screen shot 2017-07-24 at 8 36 50 am" src="https://user-images.githubusercontent.com/7064/28531727-83264e1c-704c-11e7-94c1-8035ffb0d3c7.png">

<img width="1033" alt="screen shot 2017-07-24 at 8 37 37 am" src="https://user-images.githubusercontent.com/7064/28531756-95ca04b4-704c-11e7-9491-1974a5f0de51.png">

I'm not sure how to see which pod it's coming from. The `gce/vm_ipv4` points to a kubernetes vm with nginx on it and this docker container, which looks like the most likely culprit: https://gist.github.com/whatupdave/16d3650266740f495d984aac41f71ba7

**Comment by crassirostris** [comment]
Rwhatupdave I had the hypothesis, but I confused trace and error reporting. This prometheus-to-sd container actually doesn't have the code to send anything to SD Trace, so it's not likely that it's the offender. I also haven't witnessed anything like this before with the prometheus-to-sd container

You can try to inspect the api manager and correlate the sources and e.g. some logs in the containers on the node. Also, you can try to set up a separate account for each container and check out the source service account for the calls

**Comment by whatupdave** [comment]
Ah, thanks for investigating. My new hypothesis is that google cloud load balancer is creating the span but not populating the URL or HTTP method fields.
