### ISSUE TITLE
[Feature Request] Ability to override resource labels with prometheus labels

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/k8s-stackdriver#173]
I am working on adding a [cAdvisor daemonset](https://github.com/google/cadvisor/tree/master/deploy/kubernetes) with an [example integration with the prometheus-to-sd sidecar](https://github.com/google/cadvisor/blob/master/deploy/kubernetes/overlays/examples/stackdriver-sidecar.yaml)

Prometheus-to-sd currently just uses the [namespace_id, pod_id, and container_name provided by the config](https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/prometheus-to-sd/translator/translator.go#L316).  However, for cAdvisor, or other monitoring daemonsets that publish metrics about other pods/containers in the cluster, adding namespace_id, pod_id, and container_name as prometheus labels results in stackdriver labels pointing to the "correct" container, but the monitored resource points to the cAdvisor container (as that is where the metrics originate from).

I propose either allowing prometheus labels to override the monitored resource attributes by default (if provided), or adding the ability to configure which prometheus label is used for each monitored resource attribute.  E.g. `--container-name-label`, `--pod-id-label`, etc, and allowing only these, or the `--pod-id`, `--namespace-id` flags to be set.  The latter has the advantage of being able to perform "remapping" of labels from the target pod to monitored resource attributes in stackdriver, and means we don't need to match labels exactly (e.g. I could specify `--namespace-id-label=namespace_name` if that was how the producer labeled metrics).

**Comment by x13n** [comment]
cc @loburm 

The ask to be able to change source container sounds reasonable to me, but there are at least two things we should pay attention to:
1. spoofing - is it ok for any container to tell prom-to-sd all these labels? Should there be some mechanism to control which containers are allowed to do that?
2. flags won't work once we migrate to a DaemonSet prom-to-sd, which is something we'd like to do one day.

**Comment by dashpole** [comment]
For 1), while it makes it easier to spoof, our security boundary is the google "Monitoring Metric Writer" IAM permission.  For example, I can just run a pod with prometheus-to-sd and set `--pod-id=<SPOOFED_POD_ID>` today and do the same thing if I have the correct IAM permission.

**Comment by x13n** [comment]
You're right, 1. doesn't seem to be a problem. What about 2? Maybe we should just override the labels with the ones provided as I mentioned flags are probably not the way to go. Feel free to send a PR if you need this, as we'll probably won't have the capacity in the near future.

**Comment by dashpole** [comment]
I don't really have the context on (2) to know how this would fit into the design.  I'll send a PR soon
