### ISSUE TITLE
[prometheus-to-sd] metrics are missing labels in stack driver

### ISSUE THREAD

**Issue by violetaria** [GoogleCloudPlatform/k8s-stackdriver#192]
I'm trying to get the kube-state-metrics setup and I can see metrics in stack driver, but none of them appear to have labels. When I looked at the `prometheus-to-sd` logs I see a bunch of errors like this:

```
Error in attempt to update metric descriptor googleapi: Error 400: 
Field labels had an invalid value: 
When creating metric custom.googleapis.com/kube-state-metrics/kube_service_labels: 
the metric has more than 10 labels., badRequest
```
I'm not quite sure what the issue is but I really need the labels for this to work. Any one seen this before?

**Comment by WaterKnight1998** [comment]
@violetaria I am finding the same error! How did you solve it?

**Comment by violetaria** [comment]
sorry I didn't find a fix and we ended up not using prometheus
