### ISSUE TITLE
prometheus-to-stackdriver why create cumulative metrics for histograms

### ISSUE THREAD

**Issue by LukeDefeo** [GoogleCloudPlatform/k8s-stackdriver#210]
I have been using histograms in my python app to monitor the response time of my application. Naturally histograms in prometheus have the value type Distribution in stackdriver but im unclear why this component choses Cumulative at the metric kind.

https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/c94c033cdd1854df3213fa9526e5e30dcf5c9470/prometheus-to-sd/translator/translator.go#L306

Cumulative metrics seem appropriate for counters but for prometheus Histograms wouldn't the kind being delta (or gauge) be more suitable. My response time metrics aren't graphing properly in the UI and i think its because of this.

**Comment by LukeDefeo** [comment]
Closing this as i misunderstood a few things about how prometheus works. Makes sense now

**Comment by cagataygurturk** [comment]
Can you share how did you solve this at the end?
