### ISSUE TITLE
[custom-metrics-stackdriver-adapter] new release ? 

### ISSUE THREAD

**Issue by sjoeboo** [GoogleCloudPlatform/k8s-stackdriver#229]
looking in the container registry, the least release of the metrics adapter was July 2018, over 6 months ago. Since then it looks like the ability to query for metrics across projects, as well as use `GOOGLE_APPLICATION_CREDENTIALS` have been merged. 

Can we get a new release published so these new features can be used? (Thanks!). Happy to assist with that however I can as my org has  large need for cross-project metric queries for autoscaling to go GA in GKE.

**Comment by kawych** [comment]
https://github.com/GoogleCloudPlatform/k8s-stackdriver/releases/tag/custom-metrics-stackdriver-adapter-v0.9.0
