### ISSUE TITLE
Is this project being discontinued?

### ISSUE THREAD

**Issue by rajdhandus** [GoogleCloudPlatform/k8s-stackdriver#230]
We see a similar project prop up in https://github.com/istio/istio/tree/master/mixer/adapter/stackdriver. Which one should we be using? We have a few issues that we are facing with respect to the accuracy of the metrics being reported by this adapter project. Wondering if we should be switching to the official Istio stackdriver adapter. Please let us know..

**Comment by kawych** [comment]
This project is not being discontinued. AFAICT, the istio adapter is not an adapter for custom/external metrics API, probably it serves the purpose of sending metrics out.

Feel free to report any issues wrt. the metrics accuracy, although this project simply fetches metrics from Stackdriver, so I'm not sure if improving accuracy at this stage is possible. Have you tried comparing metrics returned by this adapter with data directly from Stackdriver? What difference did you see there?
