### ISSUE TITLE
[prometheus-to-sd] Logs are too noisy when there's nothing to send

### ISSUE THREAD

**Issue by crassirostris** [GoogleCloudPlatform/k8s-stackdriver#24]
"[No metrics to send to Stackdriver](https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/prometheus-to-sd/translator/stackdriver.go#L38)" is a warning, that will be written on every collection which is really annoying. Could you please only send it once (every X) or make it V(2/4)?

**Comment by loburm** [comment]
Sure, I'll change it.

Just to write it down, the same should be changed for https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/prometheus-to-sd/translator/metric_descriptor_cache.go#L113

**Comment by crassirostris** [comment]
Thanks!
