### ISSUE TITLE
Support UNTYPED metrics

### ISSUE THREAD

**Issue by droyo** [GoogleCloudPlatform/k8s-stackdriver#261]
Prometheus has an "untyped" metric type: https://github.com/prometheus/client_model/blob/fd36f4220a901265f90734c3183c5f0c91daa0b8/ruby/lib/prometheus/client/model/metrics.pb.rb#L11

According to the docs[1], prometheus doesn't really care too much about types but in StackDriver they do matter. Currently attempting to translate any UNTYPED metrics fails because the type is not supported.

Significantly, prometheus node-exporter uses UNTYPED for some very desirable metrics.

Is there any objection to treating UNTYPED metrics as a GAUGE? This kind makes the fewest assumptions about the data points. 

[1]: https://prometheus.io/docs/instrumenting/writing_exporters/#types

**Comment by kawych** [comment]
I think it's ok and it's a change for the better, but I'll let @loburm chime in before submitting. We may consider letting the user specify the type while whitelisting.
