### ISSUE TITLE
Which project to use when integrating Prometheus with SD?  

### ISSUE THREAD

**Issue by steinwaywhw** [GoogleCloudPlatform/k8s-stackdriver#287]
Hi there, could you help update the README and clarify which project to use when integrating Prometheus with Stackdriver? 

I've seen https://cloud.google.com/monitoring/kubernetes-engine/prometheus, https://github.com/Stackdriver/stackdriver-prometheus-sidecar, and this project. And it is not entirely clear which one is the recommended one. 

Thanks!

**Comment by x13n** [comment]
Currently recommended way is what you found in GCP public docs, please follow them. (Note that they point to the second link you pasted, since you need the sidecar for Prometheus server.)
