### ISSUE TITLE
Support for Prometheus-style scraping target discovery

### ISSUE THREAD

**Issue by mmalecki** [GoogleCloudPlatform/k8s-stackdriver#289]
Prometheus supports discovery of scraping targets using pod, service and ingress annotations (`prometheus.io/scrape`, etc.).

I see in `prometheus-to-sd` we have a dynamic config source, but that only appears to fetch data about pods in `kube-system` with specified `k8s-app` set, and only does that on startup.

Would you be open to adding support for those annotations, and if so, would you accept a PR that implements them?

**Comment by x13n** [comment]
Thanks for the offer! We are not currently planning on adding dynamic discovery to prometheus-to-sd, though, so I'm going to close this.

If you want to have a proper service discovery mechanism, today you should just use Prometheus server with Stackdriver sidecar (see [the docs here](https://cloud.google.com/monitoring/kubernetes-engine/prometheus)).
