### ISSUE TITLE
Custom Metrics - Stackdriver Adapter doesn't work for clusters across multiple zones.

### ISSUE THREAD

**Issue by kawych** [GoogleCloudPlatform/k8s-stackdriver#31]

**Comment by james-masson** [comment]
Is this still true?

**Comment by kawych** [comment]
This is actually fixed as a side effect in PR: #86, but not yet released.

**Comment by kawych** [comment]
Should be fixed in latest release: https://github.com/GoogleCloudPlatform/k8s-stackdriver/releases/tag/custom-metrics-stackdriver-adapter-v0.4.0
