### ISSUE TITLE
panic() in apiserver

### ISSUE THREAD

**Issue by Jonpez2** [GoogleCloudPlatform/k8s-stackdriver#322]
My config: kubernetes on GKE, master version 1.15.9-gke.24.  

Deployed https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml as of yesterday.  I thought I might use a release, but that's noot what the docs say, so I didn't.

Published a metric via OpenCensus whose name is OpenCensus/my-service-name/my_metric; visible under that name in the GCP Metrics webpage.

Consuming that metric in HorizontalPodAutoscaler with the path custom.googleapis.com|opencensus|my-service-name|my_metric

The Autoscaler says that it can't find any values for the metric, so I go look at the logs.  I discover that the custom-metrics-stackdriver-adapter is repeatedly panicking (stack trace at the bottom of the issue).

I thought I'd do some more debugging myself, so I went to look at the code.  That line appears not to have come from the current state of the master branch; nor did it come from any other guesses (e.g. one of the custom-metrics-stackdriver-adapter tags).  So I'm not totally sure what version of the code I'm currently running, nor of how I would upgrade when the time comes.  Should I be building this myself from source?

Help please!

Stack trace of the panic:

E0422 10:21:33.402356       1 runtime.go:67] Observed a panic: runtime error: slice bounds out of range [2:1]
goroutine 122347 [running]:
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc000e5e6c0)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:103 +0xda
panic(0x173f4a0, 0xc0008a2820)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.getRequestOptions(0xc0010e9300, 0x1ad2420, 0xc0005e0c40, 0x1abe740, 0xc00020f8c0, 0x1aa1d40, 0xc0005e0a40, 0x1a7d660, 0xc0002883f0, 0x1abc580, ...)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers/get.go:159 +0x622
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers.ListResourceWithOptions.func1(0x1abce40, 0xc000026068, 0xc0010e9300)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/endpoints/handlers/get.go:109 +0x57a
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer.restfulListResourceWithOptions.func1(0xc00061dbc0, 0xc000fb2310)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:294 +0xd8
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc00061dbc0, 0xc000fb2310)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:271 +0x254
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc0007fe5a0, 0x7f22baa96438, 0xc000fe0050, 0xc0010e9300)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/emicklei/go-restful/container.go:285 +0x9a3
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/github.com/emicklei/go-restful/container.go:199
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x184fb34, 0x22, 0xc0007fe5a0, 0xc0004539d0, 0x7f22baa96438, 0xc000fe0050, 0xc0010e9300)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x4d3
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f22baa96438, 0xc000fe0050, 0xc0010e9300)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x4f8
net/http.HandlerFunc.ServeHTTP(0xc000471e40, 0x7f22baa96438, 0xc000fe0050, 0xc0010e9300)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f22baa96438, 0xc000fe0050, 0xc0010e9300)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x57b
net/http.HandlerFunc.ServeHTTP(0xc0008b6d20, 0x7f22baa96438, 0xc000fe0050, 0xc0010e9300)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f22baa96438, 0xc000fe0050, 0xc0010e9300)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1eff
net/http.HandlerFunc.ServeHTTP(0xc000471e80, 0x7f22baa96438, 0xc000fe0050, 0xc0010e9300)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f22baa96438, 0xc000fe0050, 0xc0010e9200)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:81 +0x534
net/http.HandlerFunc.ServeHTTP(0xc0004a59a0, 0x7f22baa96438, 0xc000fe0050, 0xc0010e9200)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc000e5e6c0, 0xc000255ea0, 0x1ac5f40, 0xc000fe0050, 0xc0010e9200)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0xd0
created by github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:97 +0x1b0
/
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x1abcec0, 0xc000452380, 0xc0010e9000)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc0008b6d80, 0x1abcec0, 0xc000452380, 0xc0010e9000)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x1abcec0, 0xc000452380, 0xc0010e9000)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x18c
net/http.HandlerFunc.ServeHTTP(0xc000255ee0, 0x1ab2040, 0xc000fe0030, 0xc0010e9000)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc0008b6db0, 0x1ab2040, 0xc000fe0030, 0xc0010e9000)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0004327e0, 0x1ab2040, 0xc000fe0030, 0xc0010e9000)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0x1ac5bc0, 0xc000832060, 0xc000944000, 0xc0004327e0, 0x1ab2040, 0xc000fe0030, 0xc0010e9000)
        /usr/local/go/src/net/http/server.go:3366 +0x8d
github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc0006e5380, 0xc000fe0030, 0xc0010e9000, 0xc0008b07e0)
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/golang.org/x/net/http2/server.go:2119 +0x9f
created by github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
        /go/src/github.com/GoogleCloudPlatform/k8s-stackdriver/custom-metrics-stackdriver-adapter/vendor/golang.org/x/net/http2/server.go:1853 +0x4eb

**Comment by gmarek** [comment]
@piosz - can someone take a quick look at this?

**Comment by serathius** [comment]
@kawych PTAL

**Comment by Jonpez2** [comment]
A hopefully useful update: deleting my cluster and recreating, and then reapplying the deploy script results in exactly the same panic, despite the fact that there is nothing else running on the cluster.

**Comment by Jonpez2** [comment]
Two more details that are hopefully of use:
- The panic in the log does not appear to actually result in the pod restarting.
- There are a huge number of other lnes in the log of the following form:
E0422 14:49:48.173206       1 writers.go:172] apiserver was unable to write a JSON response: http2: stream closed
E0422 14:49:48.271337       1 writers.go:172] apiserver was unable to write a JSON response: http2: stream closed
E0422 14:49:48.271483       1 writers.go:172] apiserver was unable to write a JSON response: http2: stream closed
E0422 14:49:48.271604       1 writers.go:172] apiserver was unable to write a JSON response: http2: stream closed
E0422 14:49:48.272338       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http2: stream closed"}
E0422 14:49:48.273090       1 writers.go:172] apiserver was unable to write a JSON response: http2: stream closed

**Comment by kawych** [comment]
You're using the correct image, it's build from the latest code from the repo. Can you provide specs of a minimal deployment and HPA to help reproduce the issue?

**Comment by Jonpez2** [comment]
The question is what version is 'latest'?  When I come back in a week, which commit will we look at to debug?  Also it's odd that the log lines refer to writers.go, which doesn't exist in the repo, and also I don't see how the line referenced in the panic() can actually give that error.  Entriely possible I'm missing a lot though!

OK, I will try:
I have a service called my-service-name in my cluster which uses the following Java code to publish metrics.  Doing this once and thus creating the metric appears to suffice to break the custom exporter, even without the HPA.

import io.opencensus.exporter.stats.stackdriver.StackdriverStatsExporter;

                    StackdriverStatsExporter.createAndRegister(StackdriverStatsConfiguration.builder()
                            .setProjectId(gcpProjectId)
                            .build());

Measure.MeasureLong processingLagMeasure;

        var key = "my-service-name/processing_lag";

        processingLagMeasure = Measure.MeasureLong.create(key, "The lag in processing", "s");
        View view = View.create(
                View.Name.create(key + "_last_value"),
                "The last value of the processing lag",
                processingLagMeasure,
                Aggregation.LastValue.create(),
                Collections.emptyList());

        ViewManager viewManager = Stats.getViewManager();
        viewManager.registerView(view);

Stats.getStatsRecorder().newMeasureMap().put(processingLagMeasure, 1).record();


For completeness, my HorizontalPodAutoscaler yaml looks like this:

`apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"my-service-name-autoscale","namespace":"default"},"spec":{"maxReplicas":40,"metrics":[{"pods":{"metricName":"custom.googleapis.com|opencensus|my-service-name|processing_lag_last_value","targetAverageValue":"120"},"type":"Pods"}],"minReplicas":4,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"my-service-name"}}}
  creationTimestamp: "2020-04-22T14:51:43Z"
  name: my-service-name-autoscale
  namespace: default
  resourceVersion: "21455"
  selfLink: /apis/autoscaling/v2beta1/namespaces/default/horizontalpodautoscalers/my-service-name-autoscale
  uid: 4db681a8-3125-4fbe-b581-0b8a3dd8aee7
spec:
  maxReplicas: 40
  metrics:
  - pods:
      metricName: custom.googleapis.com|opencensus|my-service-name|processing_lag_last_value
      targetAverageValue: "120"
    type: Pods
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-service-name
`

Thank you for your time!

**Comment by kawych** [comment]
It's the version from master (there was a single code change since the release). I noticed that the image was pushed without creating a release tag, so I added it manually to the corresponding commit: `custom-metrics-stackdriver-adapter-v0.10.2`.

I believe the writers.go file is a part of a dependency and sits somewhere deep in the vendor/ directory.

I'll try to reproduce the issue, but it may take me some time. To clarify a little bit, the logs "apiserver was unable to write a JSON response: http2: stream closed" are something we are aware of, but the adapter usually works despite those. Can you try running the below commands and see if one of them works:

1. kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/custom.googleapis.com|opencensus|my-service-name|processing_lag_last_value" | jq .

2. Switch <ONE_OF_PODS_IN_YOUR_DEPLOYMENT> to one of the actual pod names:
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/<ONE_OF_PODS_IN_YOUR_DEPLOYMENT>/custom.googleapis.com|opencensus|my-service-name|processing_lag_last_value" | jq .

Would be great if you could also look at the adapter logs and see which of those commands causes the panic.
"Doing this once and thus creating the metric appears to suffice to break the custom exporter, even without the HPA.".

**Comment by Jonpez2** [comment]
The first command works.  The second doesn't.  I took a look at my metrics explorer, and found the metric being published by the pod name I used, so I think the metric is there.

**Comment by Jonpez2** [comment]
I would be happy to have a call to see if I can give you more data live through a screen share if that would help?

**Comment by kawych** [comment]
So I looked into the OpenCensus library. It turns out that by default it reports metrics against k8s_container monitored resource: https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java#L510

Custom Metrics Stackdriver Adapter requires metric reported against k8s_pod for pods, that's why it doesn't find your metric. As a fix, you have two options:
1. Set the monitored resource manually, using k8s_pod resource type. Here you have an example on how to find all necessary resource labels (in case OpenCensus doesn't do it automatically, I'm not very familiar with the library): https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/custom-metrics-stackdriver-adapter/examples/direct-to-sd/sd_dummy_exporter.go#L131

2. Alternatively, take a look if using the External Metrics would work for you better.

For the panic() error, I don't see what could've caused it, but it appears as something unrelated - you mentioned above that the external metrics API works for you, so the adapter is fine. We'll continue investigating the errors in logs.

A potential future improvement is to allow for k8s_container metrics for pods. Feel free to file a feature request for this or contribute this feature.

**Comment by Jonpez2** [comment]
Thanks for the info.  I have set up all the labels as you requested, and I have checked on the metrics explorer to make sure that I am monitoring a k8s_pod.  The HPA still doesn't find the metrics, with exactly the same error message.

I will take a look at using the external metrics API.  It would be good if you could update the official GCP docs here - https://cloud.google.com/kubernetes-engine/docs/tutorials/custom-metrics-autoscaling and here  - https://cloud.google.com/monitoring/custom-metrics/open-census to show how these two recommended approaches are supposed to work together.

Thank you for your time!

**Comment by Jonpez2** [comment]
Wait no I made a mistake - it works!  I mistakenly used the pod_uid instead of the name.

Hooray!  I now have a beautifully self-scaling system.  Thank you!

So for anyone else that comes across this, the OpenCensus incantations you want are:
Use an httpclient inside your pod to get various bits of info from the compute metadata endpoint:
    private final String metadata = "http://metadata.google.internal";

    private String fetchMetadata(String key) throws IOException {
        Request request = new Request.Builder()
                .url(metadata + key)
                .addHeader("Metadata-Flavor", "Google")
                .get()
                .build();

        Response response = ok.newCall(request).execute();
        return response.body().string();
    }

    private String lastSegment(String of) {
        var path = Paths.get(of);
        return path.getName(path.getNameCount() - 1).toString();
    }

        projectId = fetchMetadata("/computeMetadata/v1/project/project-id");
        zone = lastSegment(fetchMetadata("/computeMetadata/v1/instance/zone"));
        cluster = lastSegment(fetchMetadata("/computeMetadata/v1/instance/attributes/cluster-name"));
        cluster_name = lastSegment(fetchMetadata("/computeMetadata/v1/instance/attributes/cluster-name"));
        cluster_location = lastSegment(fetchMetadata("/computeMetadata/v1/instance/attributes/cluster-location"));
        instance_id = lastSegment(fetchMetadata("/computeMetadata/v1/instance/id"));

...then use the k8s downward API (https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) to fetch some other bits - specifically the metadata.name and metadata.namespace.

and then in your Stackdriver exporter setup, set all the labels:

                    StackdriverStatsExporter.createAndRegister(StackdriverStatsConfiguration.builder()
                            .setProjectId(gcpProjectId)
                            .setMonitoredResource(com.google.cloud.MonitoredResource.newBuilder("k8s_pod")
                                    .addLabel("project_id", metadataAccess.projectId)
                                    .addLabel("location", metadataAccess.cluster_location)
                                    .addLabel("cluster_name", metadataAccess.cluster_name)
                                    .addLabel("namespace_name", metadataAccess.k8s_namespace)
                                    .addLabel("pod_name", metadataAccess.k8s_pod_name)
                                    .build()
                                    .toPb()
                            )
                            .build());

(com.google.cloud.MonitoredResource comes from com.google.cloud:google-cloud-core).
