### ISSUE TITLE
gcr.io/google-containers/custom-metrics-stackdriver-adapter:v0.11.0 not available

### ISSUE THREAD

**Issue by mingquewu-adara** [GoogleCloudPlatform/k8s-stackdriver#351]
Hello,

[gcr.io/google-containers/custom-metrics-stackdriver-adapter:v0.11.0](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/custom-metrics-stackdriver-adapter?tag=v0.11.0&gcrImageListsize=30) is not available yet.

But, in [PR #348](https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/348/files/ae968074c44c61160de3ca781a5087f3f32d9023) is updated already. This causes `ImagePullBackOff` pod error.
> Cannot pull image 'gcr.io/google-containers/custom-metrics-stackdriver-adapter:v0.11.0' from the registry.

**Comment by kawych** [comment]
Thanks for reporting this, I'll revert the image bump until the release is completed.

**Comment by mingquewu-adara** [comment]
@kawych, confirmed the revert. Thanks for taking care of this.
