### ISSUE TITLE
Where are the metrics sent from event-exporter?

### ISSUE THREAD

**Issue by tonglil** [GoogleCloudPlatform/k8s-stackdriver#41]
I spent the day digging around but could not figure out where I can see the metrics being sent from `event-exporter`.

Besides the one running in the 1.7+ GKE cluster, I even ran my own (log shows it is successfully sending metrics to Stackdriver, I created the ClusterRoleBinding), however I'm not sure where to actually see the metrics in SD (I tried to create a chart with custom metrics, but none appear).

Tailing the container gives me:
```
...
I0912 20:56:31.575763       1 sink.go:160] Sending 4 entries to Stackdriver
I0912 20:56:31.685767       1 sink.go:167] Successfully sent 4 entries to Stackdriver
...
```

Further, I want to confirm that it is exporting events `kubectl get event`?

Any guidance or README update in this would be great.

**Comment by crassirostris** [comment]
@tonglil In GKE it's configured to send metrics to a protected endpoint, to control the health of the event-exporter. We haven't yet figured out the way to expose these metrics both internally for managing purposes and externally in Stackdriver. @piosz and @loburm will have more context here

If you run it manually, replace the metric prefix in prometheus-to-sd container configuration from `container.googleapis.com/internal/addons` with e.g. `custom.googleapis.com/addons` in order to see these metrics in Stackdriver as custom metrics

**Comment by crassirostris** [comment]
> Further, I want to confirm that it is exporting events `kubectl get event`?

Yes, the events that are exported to Stackdriver are exactly the same you see by running `kubectl get event`, but in Stackdriver they are stored for up to 30 days, instead of 1 hour in Kubernetes

**Comment by tonglil** [comment]
Gotcha, is there a way I can export to both endpoints to prevent me messing with some SD future dependent feature (container.googleapis.com/internal/addons AND custom.googleapis.com/addons)?

I was actually just going to run a copy of it in my own namespace.

**Comment by tonglil** [comment]
Also, AFAIK Event Exporter does not need prom-to-sd? It has a SD sink built in.

**Comment by crassirostris** [comment]
> Gotcha, is there a way I can export to both endpoints to prevent me messing with some SD future dependent feature

You can run two prometheus-to-sd containers with both endpoints, they're pretty lightweight (~10MB and couple of millicores on average)

> Also, AFAIK Event Exporter does not need prom-to-sd? It has a SD sink built in

Stackdriver has Logging and Monitoring products. Event exporter exports Kubernetes events to Stackdriver Logging, and prometheus-to-sd container exports metrics about exporting events to Stackdriver Monitoring. So the sink in event exporter is about Stackdriver Logging actually, not Stackdriver Monitoring, so prometheus-to-sd cannot be removed

**Comment by crassirostris** [comment]
BTW, are you sure you need those metrics? They're used only to monitor the exporter health, like number of received and sent events and number of requests sent to the Stackdriver Logging API

It doesn't influence how it exports events

**Comment by tonglil** [comment]
> Event exporter exports Kubernetes events to Stackdriver Logging
Thanks, this was what I was looking for :)

**Comment by zhuchenjie** [comment]
#TYPE kubernetes_events gauge
kubernetes_events{event_kind=“Pod”,event_name=“nginx-pc-534913751-2yzev”,event_namespace=“allen”,event_reason=“BackOff”,event_source=“kube-node-3/kubelet”,event_subobject=“spec.containers{nginx}”,event_type=“Normal”} 1
kubernetes_events{event_kind=“Pod”,event_name=“nginx-pc-534913751-2yzev”,event_namespace=“allen”,event_reason=“Failed”,event_source=“kube-node-3/kubelet”,event_subobject=“spec.containers{nginx}”,event_type=“Warning”} 0
kubernetes_events{event_kind=“Pod”,event_name=“nginx-pc-534913751-2yzev”,event_namespace=“allen”,event_reason=“FailedSync_ErrImagePull”,event_source=“kube-node-3/kubelet”,event_subobject="",event_type=“Warning”} 0
kubernetes_events{event_kind=“Pod”,event_name=“nginx-pc-534913751-2yzev”,event_namespace=“allen”,event_reason=“FailedSync_ImagePullBackOff”,event_source=“kube-node-3/kubelet”,event_subobject="",event_type=“Warning”} 1
kubernetes_events{event_kind=“Pod”,event_name=“nginx-pc-534913751-2yzev”,event_namespace=“allen”,event_reason=“Pulling”,event_source=“kube-node-3/kubelet”,event_subobject=“spec.containers{nginx}”,event_type=“Normal”} 0

**Comment by zhuchenjie** [comment]
metrics from my env:
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000140144
go_gc_duration_seconds{quantile="0.25"} 0.000140144
go_gc_duration_seconds{quantile="0.5"} 0.00040924
go_gc_duration_seconds{quantile="0.75"} 0.00040924
go_gc_duration_seconds{quantile="1"} 0.00040924
go_gc_duration_seconds_sum 0.000549384
go_gc_duration_seconds_count 2
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 18
# HELP http_request_duration_microseconds The HTTP request latencies in microseconds.
# TYPE http_request_duration_microseconds summary
http_request_duration_microseconds{handler="prometheus",quantile="0.5"} NaN
http_request_duration_microseconds{handler="prometheus",quantile="0.9"} NaN
http_request_duration_microseconds{handler="prometheus",quantile="0.99"} NaN
http_request_duration_microseconds_sum{handler="prometheus"} 0
http_request_duration_microseconds_count{handler="prometheus"} 0
# HELP http_request_size_bytes The HTTP request sizes in bytes.
# TYPE http_request_size_bytes summary
http_request_size_bytes{handler="prometheus",quantile="0.5"} NaN
http_request_size_bytes{handler="prometheus",quantile="0.9"} NaN
http_request_size_bytes{handler="prometheus",quantile="0.99"} NaN
http_request_size_bytes_sum{handler="prometheus"} 0
http_request_size_bytes_count{handler="prometheus"} 0
# HELP http_response_size_bytes The HTTP response sizes in bytes.
# TYPE http_response_size_bytes summary
http_response_size_bytes{handler="prometheus",quantile="0.5"} NaN
http_response_size_bytes{handler="prometheus",quantile="0.9"} NaN
http_response_size_bytes{handler="prometheus",quantile="0.99"} NaN
http_response_size_bytes_sum{handler="prometheus"} 0
http_response_size_bytes_count{handler="prometheus"} 0
# HELP kubernetes_build_info A metric with a constant '1' value labeled by major, minor, git version, git commit, git tree state, build date, Go version, and compiler from which Kubernetes was built, and platform on which it is running.
# TYPE kubernetes_build_info gauge
kubernetes_build_info{buildDate="1970-01-01T00:00:00Z",compiler="gc",gitCommit="$Format:%H$",gitTreeState="not a git tree",gitVersion="v1.3.2+$Format:%h$",goVersion="go1.6.2",major="1",minor="3"<Plug>PeepOpenlatform="darwin/amd64"} 1
# HELP kubernetes_events State of kubernetes events
# TYPE kubernetes_events gauge
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="BackOff",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Normal"} 1
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="Failed",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Warning"} 0
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="FailedSync_ErrImagePull",event_source="kube-node-3/kubelet",event_subobject="",event_type="Warning"} 0
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="FailedSync_ImagePullBackOff",event_source="kube-node-3/kubelet",event_subobject="",event_type="Warning"} 1
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="Pulling",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Normal"} 0
# HELP last_scrape_duration_seconds Duration of the last scrape of metrics from event store.
# TYPE last_scrape_duration_seconds gauge
last_scrape_duration_seconds 5.1443e-05
# HELP last_scrape_error Whether the last scrape of metrics from event store resulted in an error (1 for error, 0 for success).
# TYPE last_scrape_error gauge
last_scrape_error 0
# HELP rest_client_request_latency_microseconds Request latency in microseconds. Broken down by verb and URL
# TYPE rest_client_request_latency_microseconds summary
rest_client_request_latency_microseconds{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET",quantile="0.5"} 155984
rest_client_request_latency_microseconds{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET",quantile="0.9"} 155984
rest_client_request_latency_microseconds{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET",quantile="0.99"} 155984
rest_client_request_latency_microseconds_sum{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET"} 155984
rest_client_request_latency_microseconds_count{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET"} 1
# HELP rest_client_request_status_codes Number of http requests, partitioned by metadata
# TYPE rest_client_request_status_codes counter
rest_client_request_status_codes{code="200",host="sysinfra.caicloudprivatetest.com",method="GET"} 2
# HELP scrapes_total Total number of times event store was scraped for metrics.
# TYPE scrapes_total counter
scrapes_total 2

**Comment by zhuchenjie** [comment]
metrics from my env:
#HELP kubernetes_events State of kubernetes events
#TYPE kubernetes_events gauge
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-yzev",event_namespace="allen",event_reason="BackOff",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Normal"} 1
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="Failed",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Warning"} 0
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="FailedSync_ErrImagePull",event_source="kube-node-3/kubelet",event_subobject="",event_type="Warning"} 0
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="FailedSync_ImagePullBackOff",event_source="kube-node-3/kubelet",event_subobject="",event_type="Warning"} 1
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="Pulling",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Normal"} 0

**Comment by zhuchenjie** [comment]
metrics from my env:
`# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000140144
go_gc_duration_seconds{quantile="0.25"} 0.000140144
go_gc_duration_seconds{quantile="0.5"} 0.00040924
go_gc_duration_seconds{quantile="0.75"} 0.00040924
go_gc_duration_seconds{quantile="1"} 0.00040924
go_gc_duration_seconds_sum 0.000549384
go_gc_duration_seconds_count 2
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 18
# HELP http_request_duration_microseconds The HTTP request latencies in microseconds.
# TYPE http_request_duration_microseconds summary
http_request_duration_microseconds{handler="prometheus",quantile="0.5"} NaN
http_request_duration_microseconds{handler="prometheus",quantile="0.9"} NaN
http_request_duration_microseconds{handler="prometheus",quantile="0.99"} NaN
http_request_duration_microseconds_sum{handler="prometheus"} 0
http_request_duration_microseconds_count{handler="prometheus"} 0
# HELP http_request_size_bytes The HTTP request sizes in bytes.
# TYPE http_request_size_bytes summary
http_request_size_bytes{handler="prometheus",quantile="0.5"} NaN
http_request_size_bytes{handler="prometheus",quantile="0.9"} NaN
http_request_size_bytes{handler="prometheus",quantile="0.99"} NaN
http_request_size_bytes_sum{handler="prometheus"} 0
http_request_size_bytes_count{handler="prometheus"} 0
# HELP http_response_size_bytes The HTTP response sizes in bytes.
# TYPE http_response_size_bytes summary
http_response_size_bytes{handler="prometheus",quantile="0.5"} NaN
http_response_size_bytes{handler="prometheus",quantile="0.9"} NaN
http_response_size_bytes{handler="prometheus",quantile="0.99"} NaN
http_response_size_bytes_sum{handler="prometheus"} 0
http_response_size_bytes_count{handler="prometheus"} 0
# HELP kubernetes_build_info A metric with a constant '1' value labeled by major, minor, git version, git commit, git tree state, build date, Go version, and compiler from which Kubernetes was built, and platform on which it is running.
# TYPE kubernetes_build_info gauge
kubernetes_build_info{buildDate="1970-01-01T00:00:00Z",compiler="gc",gitCommit="$Format:%H$",gitTreeState="not a git tree",gitVersion="v1.3.2+$Format:%h$",goVersion="go1.6.2",major="1",minor="3"<Plug>PeepOpenlatform="darwin/amd64"} 1
# HELP kubernetes_events State of kubernetes events
# TYPE kubernetes_events gauge
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="BackOff",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Normal"} 1
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="Failed",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Warning"} 0
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="FailedSync_ErrImagePull",event_source="kube-node-3/kubelet",event_subobject="",event_type="Warning"} 0
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="FailedSync_ImagePullBackOff",event_source="kube-node-3/kubelet",event_subobject="",event_type="Warning"} 1
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="Pulling",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Normal"} 0
# HELP last_scrape_duration_seconds Duration of the last scrape of metrics from event store.
# TYPE last_scrape_duration_seconds gauge
last_scrape_duration_seconds 5.1443e-05
# HELP last_scrape_error Whether the last scrape of metrics from event store resulted in an error (1 for error, 0 for success).
# TYPE last_scrape_error gauge
last_scrape_error 0
# HELP rest_client_request_latency_microseconds Request latency in microseconds. Broken down by verb and URL
# TYPE rest_client_request_latency_microseconds summary
rest_client_request_latency_microseconds{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET",quantile="0.5"} 155984
rest_client_request_latency_microseconds{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET",quantile="0.9"} 155984
rest_client_request_latency_microseconds{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET",quantile="0.99"} 155984
rest_client_request_latency_microseconds_sum{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET"} 155984
rest_client_request_latency_microseconds_count{url="https://sysinfra.caicloudprivatetest.com/api/v1/events?resourceVersion=%7Bvalue%7D",verb="GET"} 1
# HELP rest_client_request_status_codes Number of http requests, partitioned by metadata
# TYPE rest_client_request_status_codes counter
rest_client_request_status_codes{code="200",host="sysinfra.caicloudprivatetest.com",method="GET"} 2
# HELP scrapes_total Total number of times event store was scraped for metrics.
# TYPE scrapes_total counter
scrapes_total 2`

**Comment by zhuchenjie** [comment]
metrics from my environment:
`kubernetes_build_info{buildDate="1970-01-01T00:00:00Z",compiler="gc",gitCommit="$Format:%H$",gitTreeState="not a git tree",gitVersion="v1.3.2+$Format:%h$",goVersion="go1.6.2",major="1",minor="3"<Plug>PeepOpenlatform="darwin/amd64"} 1
#HELP kubernetes_events State of kubernetes events
#TYPE kubernetes_events gauge
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="BackOff",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Normal"} 1
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="Failed",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Warning"} 0
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="FailedSync_ErrImagePull",event_source="kube-node-3/kubelet",event_subobject="",event_type="Warning"} 0
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="FailedSync_ImagePullBackOff",event_source="kube-node-3/kubelet",event_subobject="",event_type="Warning"} 1
kubernetes_events{event_kind="Pod",event_name="nginx-pc-534913751-2yzev",event_namespace="allen",event_reason="Pulling",event_source="kube-node-3/kubelet",event_subobject="spec.containers{nginx}",event_type="Normal"} 0`
