### ISSUE TITLE
update README with correct image hosting location

### ISSUE THREAD

**Issue by cmosetick** [GoogleCloudPlatform/k8s-stackdriver#44]
I'm pretty sure that this image is hosted on `gcr.io` now and that the location listed in the README file is out of date.

The current location seems to be:
e.g.
`gcr.io/google-containers/fluentd-gcp`

As there is a 2.0.2 tag at that location that was updated within the last 6 months. Where as the old location has not been updated for two years. `https://hub.docker.com/r/kubernetes/fluentd-gcp/tags/`

A general overhaul of the README file would be great.

**Comment by crassirostris** [comment]
Thanks for reporting! I'll fix it shortly
