### ISSUE TITLE
custom-metrics-stackdriver-adapter - couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1

### ISSUE THREAD

**Issue by oprudkyi** [GoogleCloudPlatform/k8s-stackdriver#523]
Hi, 

after update to 1.25.6-gke.200 each run of kubectl produces warning messages (seems they didn't affect functionality though) 

```
kubectl get pods
E0304 11:26:51.613869  858314 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
```

i.e. the empty response handled as error 
```
kubectl get --raw '/apis/external.metrics.k8s.io/v1beta1'            
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"external.metrics.k8s.io/v1beta1","resources":[]}
```

it seems like a bug introduced in service discovery 
https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/146

bit KEDA has workaround https://github.com/kedacore/keda/issues/4224#issuecomment-1426749781 for this (see comment)
is there any way to have similar workaround for custom-metrics-stackdriver-adapter as well ? some sort of dummy metric ?

**Comment by oprudkyi** [comment]
original kubectl v1.25.7 doesn't have issues https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

**Comment by a-candiotti-pvotal** [comment]
i have the same pb with:
Client Version: v1.26.2
Server Version: v1.24.9-gke.3200
