### ISSUE TITLE
100% memory and CPU and never recovers

### ISSUE THREAD

**Issue by pocesar** [GoogleCloudPlatform/k8s-stackdriver#582]
The pod needs to be manually deleted so it can start working again.
![image](https://github.com/GoogleCloudPlatform/k8s-stackdriver/assets/461084/fa12f82a-3c61-4b15-8768-ea569b05bdb9)

![image](https://github.com/GoogleCloudPlatform/k8s-stackdriver/assets/461084/cc60bd13-674e-4aa9-a714-e934fa1ed6eb)

It makes all Horizontal pod autoscalers to fail, and creates a catastrophic snowball, because things can't scale up or down since it depends on this adapter

**Comment by joeyslalom** [comment]
I also encountered this issue. My workaround was to increase the deployment to 3 replicas, otherwise like the OP HPAs can't read the metric

**Comment by CatherineF-dev** [comment]
Hi @pocesar, thanks for reporting this issue.

Do you remember detailed steps to reproduce this issue?
