### ISSUE TITLE
Release new versions of prom-to-sd and fluentd-gcp

### ISSUE THREAD

**Issue by x13n** [GoogleCloudPlatform/k8s-stackdriver#98]
They need to be included in Kubernetes 1.10. This is to include PRs: https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/95 and https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/96

cc @tallclair

**Comment by x13n** [comment]
@loburm I cannot build prom-to-sd, it fails with following error:

main.go:33:2: cannot find package "github.com/GoogleCloudPlatform/k8s-stackdriver/prometheus-to-sd/config" in any of: (...)
main.go:34:2: cannot find package "github.com/GoogleCloudPlatform/k8s-stackdriver/prometheus-to-sd/flags" in any of: (...)
main.go:35:2: cannot find package "github.com/GoogleCloudPlatform/k8s-stackdriver/prometheus-to-sd/translator" in any of: (...)

Any clues what can be causing this? All I did was running make build within prometheus-to-sd dir.

**Comment by x13n** [comment]
Ok, nvm, my misconfiguration. Tests are failing though:

$ make test
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go test ./...
?   	github.com/GoogleCloudPlatform/k8s-stackdriver/prometheus-to-sd	[no test files]
# github.com/GoogleCloudPlatform/k8s-stackdriver/prometheus-to-sd/translator
translator/stackdriver.go:110: Errorf format %v reads arg #3, but call has only 2 args

**Comment by x13n** [comment]
Ok, I was able to build a container for prom-to-sd, but fluent-gcp-image one is failing:

Installing ffi (1.9.21)
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Gem::Ext::BuildError)
    ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.21/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20180213-4152-zxlwk0.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.21/mkmf.log

current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR=" clean

current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.21/ext/ffi_c
make "DESTDIR="
Running autoreconf for libffi
/var/lib/gems/2.3.0/gems/ffi-1.9.21/ext/ffi_c/libffi/autogen.sh: 2: exec: autoreconf: not found
libffi.mk:6: recipe for target '"/var/lib/gems/2.3.0/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-linux-gnu"/.libs/libffi_convenience.a' failed
make: *** ["/var/lib/gems/2.3.0/gems/ffi-1.9.21/ext/ffi_c/libffi-x86_64-linux-gnu"/.libs/libffi_convenience.a] Error 127

**Comment by crassirostris** [comment]
@x13n could you please submit a PR similar to https://github.com/kubernetes/kubernetes/pull/59665 to this repo?

**Comment by x13n** [comment]
Thanks for sharing this! I'll send one PR fixing both builds and bumping tag versions.
